# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madeproduct', to='logreg.User')),
                ('users', models.ManyToManyField(to='logreg.User')),
            ],
        ),
    ]
